; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-waku-ctl]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
	arkhipenko/TaskScheduler@^4.0.2
	ESP32Async/AsyncTCP@^3.4.1
	ESP32Async/ESPAsyncWebServer@^3.7.7
	adafruit/Adafruit SSD1306@^2.5.15
	adafruit/Adafruit GFX Library@^1.12.3
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit ADS1X15@^2.4.0
	br3ttb/PID@^1.2.1
	fastled/FastLED@^3.10.3
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_USB_MSC_ON_BOOT=0
	-DARDUINO_USB_DFU_ON_BOOT=0
extra_scripts = pre:extra_script.py
upload_port = COM18
monitor_port = COM18
