// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed tray.png
var resourceTrayPngData []byte
var resourceTrayPng = &fyne.StaticResource{
	StaticName:    "tray.png",
	StaticContent: resourceTrayPngData,
}
